version: 2
updates:
- package-ecosystem: docker
  directory: "/"
  schedule:
    interval: daily
    time: "03:00"
    timezone: Europe/London
  open-pull-requests-limit: 10
  reviewers:
  - mattempty
  - chrispymm
  - H3ll3m4
  - StevenLeighton21
- package-ecosystem: npm
  directory: "/"
  schedule:
    interval: daily
    time: "03:00"
    timezone: Europe/London
  open-pull-requests-limit: 10
  allow:
    - dependency-type: security
    - dependency-type: production
  reviewers:
  - mattempty
  - chrispymm
  - H3ll3m4
  - StevenLeighton21
